### ISSUE TITLE
The exported excel is too large

### ISSUE THREAD

**Issue by cindoralla** [salvois/LargeXlsx#10] opened 2022-07-19 09:56 UTC
Thanks for the great work! I tried to use this, and it really solved the OOM issue caused by the OpenXML SAX. However, the exported excel was too large - using OpenXML SAX, the file was about 240MB, but using LargeXlsx, it was about 1G. Please tell me  how to reduce the size. Thank you.

By the way, I have already removed all styles, and the initialize of xlsxWriter I use is :
`using (var xlsxWriter = new XlsxWriter(stream, SharpCompress.Compressors.Deflate.CompressionLevel.BestCompression, true))`

**Comment by salvois** [comment] 2022-07-19 19:22
Hello @cindoralla ,
I'm glad that LargeXlsx helped you with your OOM issues.
There can be a couple of reasons why you get a larger XLSX file.
The first could be the compression level, that you have already tried, but I don't expect it to have such a dramatic effect.
The second reason may be the strings: if you have a lot of repeated strings in your worksheets, a non-streaming XLSX writer may collect them in a lookup table, and place just a reference into a cell. Since LargeXlsx cannot know in advance all the content of the file, it cannot deduplicate strings.
If the latter is the case, you should notice a reduction in the file size if you save from Excel the file produced by LargeXlsx. You could also inspect the resulting XML files inside the XLSX zipped archive to confirm whether this is the case. If it is, I'm afraid there is no way to reduce the file size by a meaningful amount: this is by design.
Please let me know if it makes sense.
Thanks,
   Salvo

**Comment by cindoralla** [comment] 2022-07-20 06:30
@salvois Thanks for the reply. Yes, I checked the excel, and found that there were lots of duplicate texts in it. I will continue to us this great plug. Thanks again. I will close this question.

**Comment by salvois** [comment] 2022-07-23 15:05
Hi @cindoralla ,
I have played a bit and added support for shared strings to the LargeXlsx library.
The new behavior is opt-in (see the WriteSharedString method), so that you can trade memory consumption for file size.
Please let me know if that mitigates your issue!
Thanks,
   Salvo

**Comment by cindoralla** [comment] 2022-07-27 02:18
Thanks @salvois , I've tried the new feature, and unfortunately oom occurred just you mentioned. Thanks as well, and at last I decided to continue to use the former "Write", the large excel was OK at the current time.

**Comment by salvois** [comment] 2022-07-27 19:11
I am glad that at least you have reproduced and worked around your problem!
I'm closing the issue for now.
Thanks,
   Salvo

**Closed by salvois** 2022-07-27 19:11 UTC
Labels: question
